baseURL = "http://blog.without.hosting/"
languageCode = "en-us"
title = "Without hosting"
theme = "ananke"
pygmentsCodefences = true
pygmentsStyle = "pygments"
pygmentsUseClasses = true
[params]
    custom_css = ["./syntax.css"]
