baseURL = "https://blog.without.hosting/"
locale = "en-US"
title = "Without hosting"
theme = "PaperMod"
enableEmoji = true
pygmentsUseClasses = true
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[params]
  env = "production"
  author = "Wimpheling"
  description = "Wimphelings's personal website"
  keywords = ["blog", "developer", "personal"]
  dateFormat = "January 2, 2006"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowPageNums = true
  ShowRssButtonInSectionTermList = true
  ShowShareButtons = false
  ShowFullTextinRSS = false
  assets = { disableHLJS = true }

  [params.homeInfoParams]
    title = "Without hosting"
    content = "Wimphelings's personal website and blog."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/wimpheling"

  # Google Tag Manager
  [params.analytics]
    [params.analytics.google]
      SiteVerificationTag = "G-PXR780XCW2"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.x]
    disableInlineCSS = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]